//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Details
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<bool> Option_Selected { get; set; }
        public string CorrectOption { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ExamID { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
